server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto4
    username: postgres
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update

cloud:
  function:
    definition:
  stream:
    default-binder: kafka.default
    bindings:
      game@inding-out-0:
        destination: event.game-created
        binder: kafka_default
        useNativeDecoding: true
    binders:
      kafka_default:
        type: kafka
        environment:
          spring:
            cloud:
              stream:
                kafka:
                  default:
                    consumer:
                      configuration:
                        session.timeout.ms: 10000
                        max.poll.records: 10
                    producer:
                      compressionType: grip
                      configuration:
                        max.request.size: 10000
                  binder:
                    autoAddPartitions: true
                    autoCreateTopics: true
                    requiredAcks: -1
                    minPartitionCount: 3
                    replicationFactor: 1
                    serdeError: logAndContinue
                    broker: localhost:9092